### ISSUE TITLE
Update docs for Edulint 4.0 (`edulint check`)

### ISSUE THREAD

**Issue by BorysekOndrej** [GiraffeReversed/edulint#10]
[Edulint 4.0.0](https://github.com/GiraffeReversed/edulint/releases/tag/v4.0.0) introduced a breaking change where instead of calling `python3 -m edulint file.py` you should now call `python3 -m edulint check file.py`.

This is fixed in the source code of the documentation and in the source for demo gif in readme, but neither were rebuilt since that version. We should fix that.

**Comment by GiraffeReversed** [comment]
Documentation is up to date now, but we still have to fix the demo gif.

**Comment by BorysekOndrej** [comment]
Demo gif has now also been updated. Released in 4.1.1, ref https://github.com/GiraffeReversed/edulint/commit/82f4898d2d8ea9f78481c5978f247facf63c59d3.
